spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/FriendManagement
    username: sa
    password:
  jackson:
    default-property-inclusion: non_null