spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/FriendManagement
    username: root
    password: password
  jackson:
    default-property-inclusion: non_null
