version: '2'
services:
  friendmanagement:
    container_name: friend-management
    image: friend-management
    depends_on:
      - friendmanagement-db
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://friendmanagement-db:3306/FriendManagement?useUnicode=true&characterEncoding=utf8&useSSL=false
    ports:
      - 8080:8080
  friendmanagement-db:
    extends:
      file: mysql.yml
      service: friendmanagement-db
