version: '2'

services:
  friendmanagement-mysql:
    image: mysql:5.6.41
    ports:
    - "3306:3306"
#    volumes:
#    - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=FriendManagement
      - MYSQL_USER=FriendManagement
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password

#volumes:
#  mysql_data: